{% set name = "wimpy" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wimglenn/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 014d21a31980eab48b92c4210e9fdba643b79f7081c64ea9bc97f2be9db9bd58

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - wimpy

about:
  home: https://github.com/wimglenn/wimpy
  license: MIT
  license_file: LICENSE
  summary: 'Anti-copy-pasta'
  dev_url: https://github.com/wimglenn/wimpy

extra:
  recipe-maintainers:
    - ickc
